a.out: driver2.o PizzaMain.o MenuMain.o RestaurantMain.o
	g++ driver2.o PizzaMain.o MenuMain.o RestaurantMain.o

driver2.o: driver2.cpp
	g++ -c driver2.cpp

PizzaMain.o: PizzaMain.cpp
	g++ -c PizzaMain.cpp

MenuMain.o: MenuMain.cpp
	g++ -c MenuMain.cpp

Restaurant.o: RestaurantMain.cpp
	g++ -c RestaurantMain.cpp
